[build-dependencies]
cc = "1.0"
bindgen = "0.65"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"